name: Azure CI/CD - Hub de Obras - v2

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ACR_NAME: crhubdeobrasdev
  RESOURCE_GROUP: rg-hubdeobras-dev
  ACA_ENV: env-hubdeobras-dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout path
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR Login
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build and Push Hub Core
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/hub-core:${{ github.sha }} -t ${{ env.ACR_NAME }}.azurecr.io/hub-core:latest -f hub-core/Dockerfile .
          docker push ${{ env.ACR_NAME }}.azurecr.io/hub-core:${{ github.sha }}
          docker push ${{ env.ACR_NAME }}.azurecr.io/hub-core:latest

      - name: Build and Push BFF
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/bff:${{ github.sha }} -t ${{ env.ACR_NAME }}.azurecr.io/bff:latest -f bff/Dockerfile .
          docker push ${{ env.ACR_NAME }}.azurecr.io/bff:${{ github.sha }}
          docker push ${{ env.ACR_NAME }}.azurecr.io/bff:latest

      - name: Build and Push Hub Consumer
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/hub-integrator:${{ github.sha }} -t ${{ env.ACR_NAME }}.azurecr.io/hub-integrator:latest -f hub-integrator/Dockerfile .
          docker push ${{ env.ACR_NAME }}.azurecr.io/hub-integrator:${{ github.sha }}
          docker push ${{ env.ACR_NAME }}.azurecr.io/hub-integrator:latest

  deploy-backends:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Hub Core
        run: |
          az containerapp update \
            --name hub-core-app \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.ACR_NAME }}.azurecr.io/hub-core:latest

      - name: Deploy BFF
        run: |
          az containerapp update \
            --name hub-bff-app \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.ACR_NAME }}.azurecr.io/bff:latest

      - name: Deploy Hub Consumer
        run: |
          az containerapp update \
            --name hub-integrator-app \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.ACR_NAME }}.azurecr.io/hub-integrator:latest

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout path
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Build Frontend
        run: |
          npm install
          CI=false npm run build
          
      - name: Build And Deploy Frontend
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" 
          api_location: "" 
          output_location: "build"
          skip_app_build: true